CREATE TABLE [dbo].[ALLOCATION_REQUEST](
	[ORGANIZATION_GROUP_ID] [int] NOT NULL,
	[ALLOCATION_REQUEST_ID] [int] IDENTITY(1,1) NOT NULL,
	[EXPECTED_START_DATE_DD] [int] NOT NULL,
	[EXPECTED_END_DATE_DD] [int] NULL,
	[SKILLS] [varchar](4000) NOT NULL,
	[DESCRIPTION] [varchar](4000) NULL,
	[EXPECTED_START_DATE_MM] [int] NULL,
	[EXPECTED_START_DATE_YYYY] [int] NULL,
	[EXPECTED_END_DATE_MM] [int] NULL,
	[EXPECTED_END_DATE_YYYY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ALLOCATION_REQUEST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALLOCATION_REQUEST]  WITH CHECK ADD  CONSTRAINT [ALLCT_REQST_ORG_GRP_FK] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO

ALTER TABLE [dbo].[ALLOCATION_REQUEST] CHECK CONSTRAINT [ALLCT_REQST_ORG_GRP_FK]