CREATE TABLE [dbo].[ARTIFACT](
	[ARTIFACT_ID] [int] NOT NULL,
	[ARTIFACT_TYPE_ID] [int] NOT NULL,
	[TITLE] [varchar](50) NOT NULL,
	[CONTENT] [varchar](4000) NULL,
	[OWNER] [varchar](50) NULL,
	[NAME] [varchar](50) NOT NULL,
	[CMS_PATH] [varchar](4000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_TYP_ARTFCT_FK] FOREIGN KEY([ARTIFACT_TYPE_ID])
REFERENCES [dbo].[ARTIFACT_TYPE] ([ARTIFACT_TYPE_ID])
GO

ALTER TABLE [dbo].[ARTIFACT] CHECK CONSTRAINT [ARTFCT_TYP_ARTFCT_FK]