CREATE TABLE [dbo].[ARTIFACT_TAG](
	[ARTIFACT_TAG_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_TAG_ID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIFACT_TAG]  WITH CHECK ADD  CONSTRAINT [ARTFCT_ARTFCT_TAG_FK] FOREIGN KEY([ARTIFACT_TAG_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO

ALTER TABLE [dbo].[ARTIFACT_TAG] CHECK CONSTRAINT [ARTFCT_ARTFCT_TAG_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_TAG]  WITH CHECK ADD  CONSTRAINT [ARTFCT_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO

ALTER TABLE [dbo].[ARTIFACT_TAG] CHECK CONSTRAINT [ARTFCT_TAG_TAG_FK]