CREATE TABLE [dbo].[ARTIFACT_CATEGORY](
	[ARTIFACT_CATEGORY_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PARENT_ARTIFACT_CATEGORY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY]  WITH CHECK ADD  CONSTRAINT [PRNT_ARTFCT_CTG_FK] FOREIGN KEY([ARTIFACT_CATEGORY_ID])
REFERENCES [dbo].[ARTIFACT_CATEGORY] ([ARTIFACT_CATEGORY_ID])
GO

ALTER TABLE [dbo].[ARTIFACT_CATEGORY] CHECK CONSTRAINT [PRNT_ARTFCT_CTG_FK]