CREATE TABLE [dbo].[ASSIGNMENT_TYPE](
	[ASSIGNMENT_TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ASSIGNMENT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]