CREATE TABLE [dbo].[MENTOR_PROGRAM_DETAIL](
	[MENTOR_MID] [varchar](12) NOT NULL,
	[MENTEE_MID] [varchar](12) NOT NULL,
	[MENTOR_PROGRAM_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MENTOR_PROGRAM_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_MNTR_PRGRM_DTL_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[MENTOR] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_MNTR_PRGRM_DTL_FK]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK1] FOREIGN KEY([MENTOR_MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK1]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK2] FOREIGN KEY([MENTEE_MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK2]