CREATE TABLE [dbo].[MENTOR](
	[MENTOR_PROGRAM_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENTOR]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_TYPE_MNTR_FK] FOREIGN KEY([MENTOR_PROGRAM_TYPE_ID])
REFERENCES [dbo].[MENTOR_PROGRAM_TYPE] ([MENTOR_PROGRAM_TYPE_ID])
GO

ALTER TABLE [dbo].[MENTOR] CHECK CONSTRAINT [MNTR_PRGRM_TYPE_MNTR_FK]
GO
ALTER TABLE [dbo].[MENTOR]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_MNTR_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[MENTOR] CHECK CONSTRAINT [WRK_UNT_MNTR_FK]