CREATE TABLE [dbo].[MIND_ACTIVITY](
	[MIND_ACTIVITY_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHORT_DESCRIPTION] [varchar](50) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[MID] [varchar](12) NOT NULL,
	[PERCENTAGE_UTILIZATION] [int] NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
	[RESPONSIBILITY] [varchar](4000) NULL,
	[MIND_ROLE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MIND_ACTIVITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_ACTVTY_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MIND_ACTIVITY] CHECK CONSTRAINT [MIND_ACTVTY_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_MIND_ACTVTY_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[MIND_ACTIVITY] CHECK CONSTRAINT [WRK_UNT_MIND_ACTVTY_FK]