CREATE TABLE [dbo].[MIND_MINDROLE](
	[MID] [varchar](12) NOT NULL,
	[MIND_ROLE_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[MIND_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND_MINDROLE]  WITH CHECK ADD  CONSTRAINT [MIND_MINDROLE_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MIND_MINDROLE] CHECK CONSTRAINT [MIND_MINDROLE_FK]
GO
ALTER TABLE [dbo].[MIND_MINDROLE]  WITH CHECK ADD  CONSTRAINT [MIND_ROLE_MIND_FK] FOREIGN KEY([MIND_ROLE_ID])
REFERENCES [dbo].[MIND_ROLE] ([MIND_ROLE_ID])
GO

ALTER TABLE [dbo].[MIND_MINDROLE] CHECK CONSTRAINT [MIND_ROLE_MIND_FK]