CREATE TABLE [dbo].[MIND](
	[MID] [varchar](12) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PROFESSIONAL_SUMMARY] [varchar](4000) NULL,
	[EXPERIENCE_IN_MONTHS] [int] NOT NULL,
	[DESIGNATION] [varchar](50) NOT NULL,
	[BASE_LOCATION] [varchar](50) NULL,
	[QUALIFICATION] [varchar](50) NULL,
	[IS_ACTIVE] [int] NULL,
	[JOINED_DATE_DD] [int] NULL,
	[JOINED_DATE_MM] [int] NULL,
	[JOINED_DATE_YYYY] [int] NULL,
	[INACTIVE_DATE_DD] [int] NULL,
	[INACTIVE_DATE_MM] [int] NULL,
	[INACTIVE_DATE_YYYY] [int] NULL,
	[ORGANIZATION_GROUP_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND]  WITH CHECK ADD  CONSTRAINT [R_65] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO

ALTER TABLE [dbo].[MIND] CHECK CONSTRAINT [R_65]
GO
ALTER TABLE [dbo].[MIND] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]