CREATE TABLE [dbo].[MIND_TAG](
	[MID] [varchar](12) NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND_TAG]  WITH CHECK ADD  CONSTRAINT [MIND_TAG_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MIND_TAG] CHECK CONSTRAINT [MIND_TAG_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_TAG]  WITH CHECK ADD  CONSTRAINT [MIND_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO

ALTER TABLE [dbo].[MIND_TAG] CHECK CONSTRAINT [MIND_TAG_TAG_FK]