CREATE TABLE [dbo].[MIND_PROFILE_ACTIVITY](
	[PROFILE_ID] [int] NOT NULL,
	[MIND_ACTIVITY_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[MIND_ACTIVITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_PRFL_ACT_PRFL_FK] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO

ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY] CHECK CONSTRAINT [MIND_PRFL_ACT_PRFL_FK]
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_PRFLE_ACTVTY_ACTVTY_FK] FOREIGN KEY([MIND_ACTIVITY_ID])
REFERENCES [dbo].[MIND_ACTIVITY] ([MIND_ACTIVITY_ID])
GO

ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY] CHECK CONSTRAINT [MIND_PRFLE_ACTVTY_ACTVTY_FK]