CREATE TABLE [dbo].[MIND_CONTACT](
	[MID] [varchar](12) NOT NULL,
	[CONTACT_TYPE_ID] [int] NOT NULL,
	[CONTACT_TEXT] [varchar](50) NOT NULL,
	[MIND_CONTACT_ID] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MIND_CONTACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MIND_CONTACT]  WITH CHECK ADD  CONSTRAINT [MIND_CNTCT_CNTCT_TYPE_FK] FOREIGN KEY([CONTACT_TYPE_ID])
REFERENCES [dbo].[CONTACT_TYPE] ([CONTACT_TYPE_ID])
GO

ALTER TABLE [dbo].[MIND_CONTACT] CHECK CONSTRAINT [MIND_CNTCT_CNTCT_TYPE_FK]
GO
ALTER TABLE [dbo].[MIND_CONTACT]  WITH CHECK ADD  CONSTRAINT [MIND_CNTCT_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[MIND_CONTACT] CHECK CONSTRAINT [MIND_CNTCT_MIND_FK]