CREATE TABLE [dbo].[ORG_ACTIVITY](
	[ORG_ACTIVITY_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORG_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [ORG_ACTVTY_ORG_ACTVTY_TYP_FK] FOREIGN KEY([ORG_ACTIVITY_TYPE_ID])
REFERENCES [dbo].[ORG_ACTIVITY_TYPE] ([ORG_ACTIVITY_TYPE_ID])
GO

ALTER TABLE [dbo].[ORG_ACTIVITY] CHECK CONSTRAINT [ORG_ACTVTY_ORG_ACTVTY_TYP_FK]
GO
ALTER TABLE [dbo].[ORG_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_ORG_ACTVTY_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[ORG_ACTIVITY] CHECK CONSTRAINT [WRK_UNT_ORG_ACTVTY_FK]