CREATE TABLE [dbo].[ORG_ACTIVITY_TYPE](
	[ORG_ACTIVITY_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORG_ACTIVITY_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]