CREATE TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT](
	[PRE_ASSIGNMENT_ID] [int] NOT NULL,
	[ARTIFACT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PRE_ASSIGNMENT_ID] ASC,
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_PRE_ASSNMNT_ARTFCT_FK] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO

ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT] CHECK CONSTRAINT [ARTFCT_PRE_ASSNMNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [PRE_ASSNMNT_ARTFCT_FK] FOREIGN KEY([PRE_ASSIGNMENT_ID])
REFERENCES [dbo].[PRE_ASSIGNMENT] ([PRE_ASSIGNMENT_ID])
GO

ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT] CHECK CONSTRAINT [PRE_ASSNMNT_ARTFCT_FK]