CREATE TABLE [dbo].[PRE_ASSIGNMENT](
	[MID] [varchar](12) NOT NULL,
	[PROJECT_NAME] [varchar](50) NULL,
	[PRE_ASSIGNMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_DESCRIPTION] [varchar](4000) NULL,
	[TEAM_SIZE] [int] NULL,
	[ROLE_PLAYED] [varchar](50) NULL,
	[RESPONSIBILITY] [varchar](4000) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[COMPANY_NAME] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRE_ASSIGNMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [PRE_ASSGMNT_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO

ALTER TABLE [dbo].[PRE_ASSIGNMENT] CHECK CONSTRAINT [PRE_ASSGMNT_MIND_FK]