CREATE TABLE [dbo].[PROFILE_TAG](
	[PROFILE_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROFILE_TAG]  WITH CHECK ADD  CONSTRAINT [PRFL_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO

ALTER TABLE [dbo].[PROFILE_TAG] CHECK CONSTRAINT [PRFL_TAG_TAG_FK]
GO
ALTER TABLE [dbo].[PROFILE_TAG]  WITH CHECK ADD  CONSTRAINT [PROFILE_TAG_PROFILE_FK] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO

ALTER TABLE [dbo].[PROFILE_TAG] CHECK CONSTRAINT [PROFILE_TAG_PROFILE_FK]