CREATE TABLE [dbo].[PUBLICATION](
	[SUMMARY] [varchar](120) NOT NULL,
	[PUBLICATION_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [PBLCTN_PBLCTN_TYP_FK] FOREIGN KEY([PUBLICATION_TYPE_ID])
REFERENCES [dbo].[PUBLICATION_TYPE] ([PUBLICATION_TYPE_ID])
GO

ALTER TABLE [dbo].[PUBLICATION] CHECK CONSTRAINT [PBLCTN_PBLCTN_TYP_FK]
GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_PBLCTN_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[PUBLICATION] CHECK CONSTRAINT [WRK_UNT_PBLCTN_FK]