CREATE TABLE [dbo].[TAG_ASSOCIATION](
	[TAG_ID] [int] NOT NULL,
	[TAG_GROUP_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_ID] ASC,
	[TAG_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [TAG_ASSTN_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO

ALTER TABLE [dbo].[TAG_ASSOCIATION] CHECK CONSTRAINT [TAG_ASSTN_TAG_FK]
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [TAG_ASSTN_TAG_TYPE_FK] FOREIGN KEY([TAG_GROUP_ID])
REFERENCES [dbo].[TAG_GROUP] ([TAG_GROUP_ID])
GO

ALTER TABLE [dbo].[TAG_ASSOCIATION] CHECK CONSTRAINT [TAG_ASSTN_TAG_TYPE_FK]