CREATE TABLE [dbo].[WORK_UNIT_MIND](
	[WORK_UNIT_ID] [int] NOT NULL,
	[MID] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC,
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WORK_UNIT_MIND]  WITH CHECK ADD  CONSTRAINT [R_66] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[WORK_UNIT_MIND] CHECK CONSTRAINT [R_66]