CREATE TABLE [dbo].[WORK_UNIT_ARTIFACT](
	[WORK_UNIT_ID] [int] NOT NULL,
	[ARTIFACT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC,
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_WRK_UNT_ARTFCT_FK] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO

ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT] CHECK CONSTRAINT [ARTFCT_WRK_UNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_WRK_UNT_ARTFCT_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO

ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT] CHECK CONSTRAINT [WRK_UNT_WRK_UNT_ARTFCT_FK]