CREATE TABLE [dbo].[WORK_UNIT](
	[WORK_UNIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](500) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[WORK_UNIT_TYPE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WORK_UNIT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_WRK_UNT_TYP_FK] FOREIGN KEY([WORK_UNIT_TYPE])
REFERENCES [dbo].[WORKUNIT_TYPE] ([WORK_UNIT_TYPE])
GO

ALTER TABLE [dbo].[WORK_UNIT] CHECK CONSTRAINT [WRK_UNT_WRK_UNT_TYP_FK]