USE [master]
GO
/****** Object:  Database [CSGPortal]    Script Date: 3/20/2014 3:16:47 PM ******/
CREATE DATABASE [CSGPortal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CSGPortal', FILENAME = N'D:\Data\CSGPortal.mdf' , SIZE = 36864KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CSGPortal_log', FILENAME = N'D:\Data\CSGPortal_log.ldf' , SIZE = 12352KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CSGPortal] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CSGPortal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CSGPortal] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CSGPortal] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CSGPortal] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CSGPortal] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CSGPortal] SET ARITHABORT OFF 
GO
ALTER DATABASE [CSGPortal] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CSGPortal] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [CSGPortal] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CSGPortal] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CSGPortal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CSGPortal] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CSGPortal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CSGPortal] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CSGPortal] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CSGPortal] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CSGPortal] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CSGPortal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CSGPortal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CSGPortal] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CSGPortal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CSGPortal] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CSGPortal] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CSGPortal] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CSGPortal] SET RECOVERY FULL 
GO
ALTER DATABASE [CSGPortal] SET  MULTI_USER 
GO
ALTER DATABASE [CSGPortal] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CSGPortal] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CSGPortal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CSGPortal] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CSGPortal', N'ON'
GO
USE [CSGPortal]
GO
/****** Object:  User [CSGDbUser]    Script Date: 3/20/2014 3:16:48 PM ******/
CREATE USER [CSGDbUser] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [CSGDbUser]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [CSGDbUser]
GO
ALTER ROLE [db_datareader] ADD MEMBER [CSGDbUser]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [CSGDbUser]
GO
/****** Object:  UserDefinedTableType [dbo].[UDTT_MindContact]    Script Date: 3/20/2014 3:16:49 PM ******/
CREATE TYPE [dbo].[UDTT_MindContact] AS TABLE(
	[MID] [varchar](12) NULL,
	[ContactTypeId] [int] NULL,
	[ContactText] [varchar](50) NULL
)
GO
/****** Object:  StoredProcedure [dbo].[ELMAH_GetErrorsXml]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ELMAH_GetErrorsXml]
(
    @Application NVARCHAR(60),
    @PageIndex INT = 0,
    @PageSize INT = 15,
    @TotalCount INT OUTPUT
)
AS 

    SET NOCOUNT ON

    DECLARE @FirstTimeUTC DATETIME
    DECLARE @FirstSequence INT
    DECLARE @StartRow INT
    DECLARE @StartRowIndex INT

    SELECT 
        @TotalCount = COUNT(1) 
    FROM 
        [ELMAH_Error]
    WHERE 
        [Application] = @Application

    -- Get the ID of the first error for the requested page

    SET @StartRowIndex = @PageIndex * @PageSize + 1

    IF @StartRowIndex <= @TotalCount
    BEGIN

        SET ROWCOUNT @StartRowIndex

        SELECT  
            @FirstTimeUTC = [TimeUtc],
            @FirstSequence = [Sequence]
        FROM 
            [ELMAH_Error]
        WHERE   
            [Application] = @Application
        ORDER BY 
            [TimeUtc] DESC, 
            [Sequence] DESC

    END
    ELSE
    BEGIN

        SET @PageSize = 0

    END

    -- Now set the row count to the requested page size and get
    -- all records below it for the pertaining application.

    SET ROWCOUNT @PageSize

    SELECT 
        errorId     = [ErrorId], 
        application = [Application],
        host        = [Host], 
        type        = [Type],
        source      = [Source],
        message     = [Message],
        [user]      = [User],
        statusCode  = [StatusCode], 
        time        = CONVERT(VARCHAR(50), [TimeUtc], 126) + 'Z'
    FROM 
        [ELMAH_Error] error
    WHERE
        [Application] = @Application
    AND
        [TimeUtc] <= @FirstTimeUTC
    AND 
        [Sequence] <= @FirstSequence
    ORDER BY
        [TimeUtc] DESC, 
        [Sequence] DESC
    FOR
        XML AUTO





GO
/****** Object:  StoredProcedure [dbo].[ELMAH_GetErrorXml]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ELMAH_GetErrorXml]
(
    @Application NVARCHAR(60),
    @ErrorId UNIQUEIDENTIFIER
)
AS

    SET NOCOUNT ON

    SELECT 
        [AllXml]
    FROM 
        [ELMAH_Error]
    WHERE
        [ErrorId] = @ErrorId
    AND
        [Application] = @Application





GO
/****** Object:  StoredProcedure [dbo].[ELMAH_LogError]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ELMAH_LogError]
(
    @ErrorId UNIQUEIDENTIFIER,
    @Application NVARCHAR(60),
    @Host NVARCHAR(30),
    @Type NVARCHAR(100),
    @Source NVARCHAR(60),
    @Message NVARCHAR(500),
    @User NVARCHAR(50),
    @AllXml NTEXT,
    @StatusCode INT,
    @TimeUtc DATETIME
)
AS

    SET NOCOUNT ON

    INSERT
    INTO
        [ELMAH_Error]
        (
            [ErrorId],
            [Application],
            [Host],
            [Type],
            [Source],
            [Message],
            [User],
            [AllXml],
            [StatusCode],
            [TimeUtc]
        )
    VALUES
        (
            @ErrorId,
            @Application,
            @Host,
            @Type,
            @Source,
            @Message,
            @User,
            @AllXml,
            @StatusCode,
            @TimeUtc
        )





GO
/****** Object:  StoredProcedure [dbo].[sp_get_mindprofile]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




CREATE procedure [dbo].[sp_get_mindprofile]   

AS
    SET NOCOUNT ON
	
	SELECT MID,NAME,PROFESSIONAL_SUMMARY,EXPERIENCE_IN_MONTHS,DESIGNATION,BASE_LOCATION,QUALIFICATION,
	REPLACE(CONVERT(CHAR(10),(CONVERT(VARCHAR,JOINED_DATE_DD) + '-' + 
			CONVERT(VARCHAR,JOINED_DATE_MM) + '-' + CONVERT(VARCHAR,JOINED_DATE_YYYY)),103),'/','')
	AS JOINED_DATE
	FROM MIND
	WHERE IS_ACTIVE = 1



GO
/****** Object:  StoredProcedure [dbo].[SP_INSERT_MINDDETAILS]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_MINDDETAILS]
@mid varchar(12),
@name varchar(50),
@professionSummary varchar(4000),
@experienceInMonths int,
@designation varchar(50),
@baseLocation varchar(50),
@qualification varchar(50),
@isActive int,
@joinedDate varchar(10),
@inactiveDate varchar(10),
@organizationGroupId int

AS
SET NOCOUNT ON

BEGIN

-- split the date value to DD,MM & YYYY
DECLARE @joinedDD int,@joinedMM int,@joinedYYYY int
-- sample date value 19-10-2011
	set @joinedDD = CONVERT(int,SUBSTRING(@joinedDate,1,2))
	set @joinedMM = CONVERT(int,SUBSTRING(@joinedDate,4,2))
	set @joinedYYYY = CONVERT(int,SUBSTRING(@joinedDate,7,4))

INSERT INTO MIND 
	(MID,NAME,PROFESSIONAL_SUMMARY,EXPERIENCE_IN_MONTHS,DESIGNATION,BASE_LOCATION,
	QUALIFICATION,IS_ACTIVE,JOINED_DATE_DD,JOINED_DATE_MM,JOINED_DATE_YYYY,INACTIVE_DATE_DD,INACTIVE_DATE_MM,INACTIVE_DATE_YYYY,
	ORGANIZATION_GROUP_ID)
VALUES
	(@mid,@name,@professionSummary,@experienceInMonths,@designation,@baseLocation,
	@qualification,@isActive,@joinedDD,@joinedMM,@joinedYYYY,null,null,null,@organizationGroupId)

END




GO
/****** Object:  StoredProcedure [dbo].[USP_FetchActiveMIds]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_FetchActiveMIds]
   
AS

BEGIN
    SET NOCOUNT ON
	SELECT MID FROM MIND WHERE IS_ACTIVE<>0
END


GO
/****** Object:  StoredProcedure [dbo].[USP_FetchMIds]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_FetchMIds]
   
AS

BEGIN
    SET NOCOUNT ON
	SELECT MID FROM MIND 
END


GO
/****** Object:  StoredProcedure [dbo].[USP_FetchMindContacts]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_FetchMindContacts]
@Mid varchar(12)

AS
SET NOCOUNT ON

BEGIN

SELECT 
	MID,
	MIND_CONTACT.CONTACT_TYPE_ID AS ContactTypeId,
	CONTACT_TEXT AS ContactText,
	MIND_CONTACT_ID AS MindContactId,
	CONTACT_TYPE.NAME AS Name
FROM 
MIND_CONTACT
INNER JOIN CONTACT_TYPE
ON MIND_CONTACT.CONTACT_TYPE_ID = CONTACT_TYPE.CONTACT_TYPE_ID
WHERE MID=@Mid

END


GO
/****** Object:  StoredProcedure [dbo].[USP_GetAllMinds]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[USP_GetAllMinds]
AS
BEGIN

	SELECT 
		[MID] as [MID],
		[NAME] as [Name],
		[PROFESSIONAL_SUMMARY] as [ProfessionalSummary],
		[EXPERIENCE_IN_MONTHS] as [ExperienceInMonths],
		[DESIGNATION] as [Designation],
		[BASE_LOCATION] as [BaseLocation],
		[QUALIFICATION] as [Qualification],
		[IS_ACTIVE] as [IsActive],
		[JOINED_DATE_DD] as [JoinedDateDD],
		[JOINED_DATE_MM] as [JoinedDateMM],
		[JOINED_DATE_YYYY] as [JoinedDateYYYY],
		[INACTIVE_DATE_DD] as [InactiveDateDD],
		[INACTIVE_DATE_MM] as [InactiveDateMM],
		[INACTIVE_DATE_YYYY] as [InactiveDateYYYY]
	FROM 
		[dbo].[MIND]

END




GO
/****** Object:  StoredProcedure [dbo].[USP_GetMindById]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_GetMindById]
	@mid NVARCHAR(12)
AS
BEGIN

	SELECT 
		[MID],
		[NAME],
		[PROFESSIONAL_SUMMARY] as ProfessionalSummary,
		[EXPERIENCE_IN_MONTHS] as ExperienceInMonths,
		[DESIGNATION],
		[BASE_LOCATION] as BaseLocation,
		[QUALIFICATION],
		[IS_ACTIVE] as IsActive,
		[JOINED_DATE_DD] as JoinedDateDD,
		[JOINED_DATE_MM] as JoinedDateMM,
		[JOINED_DATE_YYYY] as JoinedDateYYYY,
		[INACTIVE_DATE_DD] as InactiveDateDD,
		[INACTIVE_DATE_MM] as InactiveDateMM,
		[INACTIVE_DATE_YYYY] as InactiveDateYYYY
	FROM 
		[dbo].[MIND]
	WHERE
		[MID] = @mid;

END



GO
/****** Object:  StoredProcedure [dbo].[USP_SaveContact]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO






CREATE PROCEDURE [dbo].[USP_SaveContact]
@contacts UDTT_MindContact readonly

AS
SET NOCOUNT ON

BEGIN

SET NOCOUNT ON;
	UPDATE MIND_CONTACT 
	    set CONTACT_TEXT=c.ContactText from MIND_CONTACT as m inner join @contacts as c on (m.MID=c.MID and m.CONTACT_TYPE_ID=c.ContactTypeId) 
		  where (c.ContactText is not null and c.ContactText<>'');
	
	DELETE  MIND_CONTACT from MIND_CONTACT as m inner join @contacts as c on (m.MID=c.MID and m.CONTACT_TYPE_ID=c.ContactTypeId) 
	     where (c.ContactText is null or c.ContactText='') 

	INSERT  into MIND_CONTACT(MID,CONTACT_TYPE_ID,CONTACT_TEXT) 
	    select * from @contacts as c where not exists(select  MID from MIND_CONTACT where MID=c.MID and CONTACT_TYPE_ID=c.ContactTypeId) and (c.ContactText is not null and c.ContactText<>'') 
END






GO
/****** Object:  StoredProcedure [dbo].[USP_SaveContactOld]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_SaveContactOld]
@Mid varchar(12),
@MindContactTypeId int,
@ContactText varchar(50)

AS
SET NOCOUNT ON

BEGIN

IF NOT EXISTS(SELECT TOP 1 MID FROM MIND_CONTACT WHERE MID=@Mid AND CONTACT_TYPE_ID=@MindContactTypeId)
BEGIN
	IF @ContactText IS NOT NULL
	INSERT INTO MIND_CONTACT(
		MID,
		CONTACT_TYPE_ID,
		CONTACT_TEXT
	)
	VALUES(
		@Mid,
		@MindContactTypeId,
		@ContactText
	)
END
ELSE
BEGIN
IF @ContactText IS NOT NULL AND @ContactText<>''
	UPDATE MIND_CONTACT
		SET
			CONTACT_TEXT=@ContactText
		WHERE MID=@Mid AND CONTACT_TYPE_ID=@MindContactTypeId
ELSE
	DELETE FROM MIND_CONTACT
		WHERE MID=@Mid AND CONTACT_TYPE_ID=@MindContactTypeId
END
END

GO
/****** Object:  StoredProcedure [dbo].[USP_SaveMind]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[USP_SaveMind]

   @MID varchar(12),
   @Name varchar(50),
   @ProfessionalSummary varchar(4000)=NULL,
   @ExperienceInMonths int,
   @Designation varchar(50),
   @BaseLocation varchar(50)=NULL,
   @Qualification varchar(50)=NULL,
   @IsActive int=NULL,
   @JoinedDateDD int=NULL,
   @JoinedDateMM int=NULL,
   @JoinedDateYYYY int=NULL,
   @InactiveDateDD int=NULL,
   @InactiveDateMM int=NULL,
   @InactiveDateYYYY int=NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
    IF EXISTS(SELECT TOP 1 MID FROM [dbo].[MIND] WHERE MID=@MID)

UPDATE MIND SET
	NAME=@Name,
	PROFESSIONAL_SUMMARY=@ProfessionalSummary,
	EXPERIENCE_IN_MONTHS=@ExperienceInMonths,
	DESIGNATION=@Designation,
	BASE_LOCATION=@BaseLocation,
	QUALIFICATION=@Qualification,
	IS_ACTIVE=@IsActive,
	JOINED_DATE_DD=@JoinedDateDD,
	JOINED_DATE_MM=@JoinedDateMM,
	JOINED_DATE_YYYY=@JoinedDateYYYY,
	INACTIVE_DATE_DD=@InactiveDateDD,
	INACTIVE_DATE_MM=@InactiveDateMM,
	INACTIVE_DATE_YYYY=@InactiveDateYYYY

	WHERE MID=@MID
ELSE

INSERT INTO MIND (
	MID,
	NAME,
	PROFESSIONAL_SUMMARY,
	EXPERIENCE_IN_MONTHS,
	DESIGNATION,
	BASE_LOCATION,
	QUALIFICATION,
	IS_ACTIVE,
	JOINED_DATE_DD,
	JOINED_DATE_MM,
	JOINED_DATE_YYYY,
	INACTIVE_DATE_DD,
	INACTIVE_DATE_MM,
	INACTIVE_DATE_YYYY
	)
VALUES(
	@MID,
	@Name ,
	@ProfessionalSummary,
	@ExperienceInMonths,
	@Designation,
	@BaseLocation,
	@Qualification,
	1,
	@JoinedDateDD,
	@JoinedDateMM,
	@JoinedDateYYYY,
	@InactiveDateDD,
	@InactiveDateMM,
	@InactiveDateYYYY
	)
END



GO
/****** Object:  StoredProcedure [dbo].[USP_SaveProfile]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO





CREATE PROCEDURE [dbo].[USP_SaveProfile]
@MID varchar(12),
   @Name varchar(50),
   @ProfessionalSummary varchar(4000)=NULL,
   @ExperienceInMonths int,
   @Designation varchar(50),
   @BaseLocation varchar(50)=NULL,
   @Qualification varchar(50)=NULL,
   @IsActive int=NULL,
   @JoinedDateDD int=NULL,
   @JoinedDateMM int=NULL,
   @JoinedDateYYYY int=NULL,
   @InactiveDateDD int=NULL,
   @InactiveDateMM int=NULL,
   @InactiveDateYYYY int=NULL,
   @contacts UDTT_MindContact readonly

AS
SET NOCOUNT ON

BEGIN

    exec USP_SaveMind @MID,@Name,@ProfessionalSummary,@ExperienceInMonths,@Designation,@BaseLocation,@Qualification,@IsActive,@JoinedDateDD,@JoinedDateMM,@JoinedDateYYYY,@InactiveDateDD,@InactiveDateMM,@InactiveDateYYYY
	exec USP_SaveContact @contacts
END



SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_GetArchitectCount]
  @ArchitectCount int out
AS
  SET NOCOUNT ON
  BEGIN
	select @ArchitectCount= COUNT(1) FROM [dbo].[MIND] where IS_ACTIVE=1
  END

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[USP_IsMindInPortal]
	-- Add the parameters for the stored procedure here
	 @MID varchar(12),
	 @result int out
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	select @result=count(1) from dbo.MIND 
	               where exists(select 1 from dbo.MIND
				     where MID=@MID)
	
END


/****** Object:  Table [dbo].[ALLOCATION_REQUEST]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ALLOCATION_REQUEST](
	[ORGANIZATION_GROUP_ID] [int] NOT NULL,
	[ALLOCATION_REQUEST_ID] [int] IDENTITY(1,1) NOT NULL,
	[EXPECTED_START_DATE_DD] [int] NOT NULL,
	[EXPECTED_END_DATE_DD] [int] NULL,
	[SKILLS] [varchar](4000) NOT NULL,
	[DESCRIPTION] [varchar](4000) NULL,
	[EXPECTED_START_DATE_MM] [int] NULL,
	[EXPECTED_START_DATE_YYYY] [int] NULL,
	[EXPECTED_END_DATE_MM] [int] NULL,
	[EXPECTED_END_DATE_YYYY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ALLOCATION_REQUEST_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ARTIFACT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARTIFACT](
	[ARTIFACT_ID] [int] NOT NULL,
	[ARTIFACT_TYPE_ID] [int] NOT NULL,
	[TITLE] [varchar](50) NOT NULL,
	[CONTENT] [varchar](4000) NULL,
	[OWNER] [varchar](50) NULL,
	[NAME] [varchar](50) NOT NULL,
	[CMS_PATH] [varchar](4000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ARTIFACT_CATEGORY]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARTIFACT_CATEGORY](
	[ARTIFACT_CATEGORY_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PARENT_ARTIFACT_CATEGORY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ARTIFACT_CATEGORY_REL]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTIFACT_CATEGORY_REL](
	[ARTIFACT_ID] [int] NOT NULL,
	[ARTIFACT_CATEGORY_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_ID] ASC,
	[ARTIFACT_CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ARTIFACT_TAG]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTIFACT_TAG](
	[ARTIFACT_TAG_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_TAG_ID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ARTIFACT_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ARTIFACT_TYPE](
	[ARTIFACT_TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ARTIFACT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ASSIGNMENT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ASSIGNMENT](
	[ORGANIZATION_GROUP_ID] [int] NOT NULL,
	[MPOWER_ID] [varchar](50) NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[DESCRIPTION] [varchar](4000) NULL,
	[TEAM_SIZE] [int] NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
	[ASSIGNMENT_TYPE_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ASSIGNMENT_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ASSIGNMENT_TYPE](
	[ASSIGNMENT_TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ASSIGNMENT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CONTACT_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONTACT_TYPE](
	[CONTACT_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CONTACT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[CUSTOMER_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[GEOGRAPHY] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ELMAH_Error]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELMAH_Error](
	[ErrorId] [uniqueidentifier] NOT NULL,
	[Application] [nvarchar](60) NOT NULL,
	[Host] [nvarchar](50) NOT NULL,
	[Type] [nvarchar](100) NOT NULL,
	[Source] [nvarchar](60) NOT NULL,
	[Message] [nvarchar](500) NOT NULL,
	[User] [nvarchar](50) NOT NULL,
	[StatusCode] [int] NOT NULL,
	[TimeUtc] [datetime] NOT NULL,
	[Sequence] [int] IDENTITY(1,1) NOT NULL,
	[AllXml] [ntext] NOT NULL,
 CONSTRAINT [PK_ELMAH_Error] PRIMARY KEY NONCLUSTERED 
(
	[ErrorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[EVENT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EVENT](
	[EVENT_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[EVENT_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[EVENT_TYPE](
	[EVENT_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EVENT_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MENTOR]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MENTOR](
	[MENTOR_PROGRAM_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MENTOR_PROGRAM_DETAIL]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MENTOR_PROGRAM_DETAIL](
	[MENTOR_MID] [varchar](12) NOT NULL,
	[MENTEE_MID] [varchar](12) NOT NULL,
	[MENTOR_PROGRAM_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MENTOR_PROGRAM_DETAIL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MENTOR_PROGRAM_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MENTOR_PROGRAM_TYPE](
	[MENTOR_PROGRAM_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MENTOR_PROGRAM_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND](
	[MID] [varchar](12) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PROFESSIONAL_SUMMARY] [varchar](4000) NULL,
	[EXPERIENCE_IN_MONTHS] [int] NOT NULL,
	[DESIGNATION] [varchar](50) NOT NULL,
	[BASE_LOCATION] [varchar](50) NULL,
	[QUALIFICATION] [varchar](50) NULL,
	[IS_ACTIVE] [int] NULL,
	[JOINED_DATE_DD] [int] NULL,
	[JOINED_DATE_MM] [int] NULL,
	[JOINED_DATE_YYYY] [int] NULL,
	[INACTIVE_DATE_DD] [int] NULL,
	[INACTIVE_DATE_MM] [int] NULL,
	[INACTIVE_DATE_YYYY] [int] NULL,
	[ORGANIZATION_GROUP_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_ACTIVITY]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_ACTIVITY](
	[MIND_ACTIVITY_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHORT_DESCRIPTION] [varchar](50) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[MID] [varchar](12) NOT NULL,
	[PERCENTAGE_UTILIZATION] [int] NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
	[RESPONSIBILITY] [varchar](4000) NULL,
	[MIND_ROLE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[MIND_ACTIVITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_CONTACT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_CONTACT](
	[MID] [varchar](12) NOT NULL,
	[CONTACT_TYPE_ID] [int] NOT NULL,
	[CONTACT_TEXT] [varchar](50) NOT NULL,
	[MIND_CONTACT_ID] [int] IDENTITY(1,1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MIND_CONTACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_MINDROLE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_MINDROLE](
	[MID] [varchar](12) NOT NULL,
	[MIND_ROLE_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[MIND_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_ORGANIZATION]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_ORGANIZATION](
	[MID] [varchar](12) NOT NULL,
	[ORGANIZATION_GROUP_ID] [int] NOT NULL,
	[START_DATE_DD] [int] NOT NULL,
	[START_DATE_MM] [int] NOT NULL,
	[START_DATE_YYYY] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[ORGANIZATION_GROUP_ID] ASC,
	[START_DATE_DD] ASC,
	[START_DATE_MM] ASC,
	[START_DATE_YYYY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_PROFILE_ACTIVITY]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MIND_PROFILE_ACTIVITY](
	[PROFILE_ID] [int] NOT NULL,
	[MIND_ACTIVITY_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[MIND_ACTIVITY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MIND_ROLE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_ROLE](
	[MIND_ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MIND_ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MIND_TAG]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MIND_TAG](
	[MID] [varchar](12) NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORG_ACTIVITY]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORG_ACTIVITY](
	[ORG_ACTIVITY_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ORG_ACTIVITY_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORG_ACTIVITY_TYPE](
	[ORG_ACTIVITY_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORG_ACTIVITY_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[ORGANIZATION_GROUP]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ORGANIZATION_GROUP](
	[ORGANIZATION_GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ORGANIZATION_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRE_ASSIGNMENT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PRE_ASSIGNMENT](
	[MID] [varchar](12) NOT NULL,
	[PROJECT_NAME] [varchar](50) NULL,
	[PRE_ASSIGNMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_DESCRIPTION] [varchar](4000) NULL,
	[TEAM_SIZE] [int] NULL,
	[ROLE_PLAYED] [varchar](50) NULL,
	[RESPONSIBILITY] [varchar](4000) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[COMPANY_NAME] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRE_ASSIGNMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PRE_ASSIGNMENT_ARTIFACT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT](
	[PRE_ASSIGNMENT_ID] [int] NOT NULL,
	[ARTIFACT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PRE_ASSIGNMENT_ID] ASC,
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROFILE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROFILE](
	[PROFILE_ID] [int] IDENTITY(1,1) NOT NULL,
	[MID] [varchar](12) NOT NULL,
	[PROFILE_TYPE_ID] [int] NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PROFILE_ARTIFACT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROFILE_ARTIFACT](
	[PROFILE_ID] [int] NOT NULL,
	[ARTIFACT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROFILE_PRE_ASSIGNMENT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROFILE_PRE_ASSIGNMENT](
	[PROFILE_ID] [int] NOT NULL,
	[PRE_ASSIGNMENT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[PRE_ASSIGNMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROFILE_TAG]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROFILE_TAG](
	[PROFILE_ID] [int] NOT NULL,
	[TAG_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_ID] ASC,
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PROFILE_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PROFILE_TYPE](
	[PROFILE_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PROFILE_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLICATION]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBLICATION](
	[SUMMARY] [varchar](120) NOT NULL,
	[PUBLICATION_TYPE_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PUBLICATION_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PUBLICATION_TYPE](
	[PUBLICATION_TYPE_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PUBLICATION_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TAG]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAG](
	[TAG_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TAG_ASSOCIATION]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAG_ASSOCIATION](
	[TAG_ID] [int] NOT NULL,
	[TAG_GROUP_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_ID] ASC,
	[TAG_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TAG_GROUP]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAG_GROUP](
	[TAG_GROUP_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](50) NOT NULL,
	[PARENT_TAG_GROUP_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[WORK_UNIT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[WORK_UNIT](
	[WORK_UNIT_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](500) NULL,
	[START_DATE_DD] [int] NULL,
	[START_DATE_MM] [int] NULL,
	[START_DATE_YYYY] [int] NULL,
	[END_DATE_DD] [int] NULL,
	[END_DATE_MM] [int] NULL,
	[END_DATE_YYYY] [int] NULL,
	[WORK_UNIT_TYPE] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[WORK_UNIT_ARTIFACT]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORK_UNIT_ARTIFACT](
	[WORK_UNIT_ID] [int] NOT NULL,
	[ARTIFACT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC,
	[ARTIFACT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[WORK_UNIT_MIND]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[WORK_UNIT_MIND](
	[WORK_UNIT_ID] [int] NOT NULL,
	[MID] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_ID] ASC,
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[WORK_UNIT_TAG]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORK_UNIT_TAG](
	[TAG_ID] [int] NOT NULL,
	[WORK_UNIT_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TAG_ID] ASC,
	[WORK_UNIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[WORKUNIT_TYPE]    Script Date: 3/20/2014 3:16:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[WORKUNIT_TYPE](
	[WORK_UNIT_TYPE] [int] NOT NULL,
	[TYPE_TEXT] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[WORK_UNIT_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_ELMAH_Error_App_Time_Seq]    Script Date: 3/20/2014 3:16:49 PM ******/
CREATE NONCLUSTERED INDEX [IX_ELMAH_Error_App_Time_Seq] ON [dbo].[ELMAH_Error]
(
	[Application] ASC,
	[TimeUtc] DESC,
	[Sequence] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELMAH_Error] ADD  CONSTRAINT [DF_ELMAH_Error_ErrorId]  DEFAULT (newid()) FOR [ErrorId]
GO
ALTER TABLE [dbo].[MIND] ADD  DEFAULT ((1)) FOR [IS_ACTIVE]
GO
ALTER TABLE [dbo].[ALLOCATION_REQUEST]  WITH CHECK ADD  CONSTRAINT [ALLCT_REQST_ORG_GRP_FK] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO
ALTER TABLE [dbo].[ALLOCATION_REQUEST] CHECK CONSTRAINT [ALLCT_REQST_ORG_GRP_FK]
GO
ALTER TABLE [dbo].[ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_TYP_ARTFCT_FK] FOREIGN KEY([ARTIFACT_TYPE_ID])
REFERENCES [dbo].[ARTIFACT_TYPE] ([ARTIFACT_TYPE_ID])
GO
ALTER TABLE [dbo].[ARTIFACT] CHECK CONSTRAINT [ARTFCT_TYP_ARTFCT_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY]  WITH CHECK ADD  CONSTRAINT [PRNT_ARTFCT_CTG_FK] FOREIGN KEY([ARTIFACT_CATEGORY_ID])
REFERENCES [dbo].[ARTIFACT_CATEGORY] ([ARTIFACT_CATEGORY_ID])
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY] CHECK CONSTRAINT [PRNT_ARTFCT_CTG_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY_REL]  WITH CHECK ADD  CONSTRAINT [ARTFCT_ARTFCT_CTGRY_REL_FK] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY_REL] CHECK CONSTRAINT [ARTFCT_ARTFCT_CTGRY_REL_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY_REL]  WITH CHECK ADD  CONSTRAINT [ARTFCT_CTG_ARTFCT_CTG_REL_FK] FOREIGN KEY([ARTIFACT_CATEGORY_ID])
REFERENCES [dbo].[ARTIFACT_CATEGORY] ([ARTIFACT_CATEGORY_ID])
GO
ALTER TABLE [dbo].[ARTIFACT_CATEGORY_REL] CHECK CONSTRAINT [ARTFCT_CTG_ARTFCT_CTG_REL_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_TAG]  WITH CHECK ADD  CONSTRAINT [ARTFCT_ARTFCT_TAG_FK] FOREIGN KEY([ARTIFACT_TAG_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO
ALTER TABLE [dbo].[ARTIFACT_TAG] CHECK CONSTRAINT [ARTFCT_ARTFCT_TAG_FK]
GO
ALTER TABLE [dbo].[ARTIFACT_TAG]  WITH CHECK ADD  CONSTRAINT [ARTFCT_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO
ALTER TABLE [dbo].[ARTIFACT_TAG] CHECK CONSTRAINT [ARTFCT_TAG_TAG_FK]
GO
ALTER TABLE [dbo].[ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [ASSGMNT_ASSGMNT_TYP_FK] FOREIGN KEY([ASSIGNMENT_TYPE_ID])
REFERENCES [dbo].[ASSIGNMENT_TYPE] ([ASSIGNMENT_TYPE_ID])
GO
ALTER TABLE [dbo].[ASSIGNMENT] CHECK CONSTRAINT [ASSGMNT_ASSGMNT_TYP_FK]
GO
ALTER TABLE [dbo].[ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [ASSGNMNT_CSTMR_FK] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMER] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[ASSIGNMENT] CHECK CONSTRAINT [ASSGNMNT_CSTMR_FK]
GO
ALTER TABLE [dbo].[ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [ORG_GRP_PROFILE_FK] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO
ALTER TABLE [dbo].[ASSIGNMENT] CHECK CONSTRAINT [ORG_GRP_PROFILE_FK]
GO
ALTER TABLE [dbo].[ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_ASSGNMNT_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[ASSIGNMENT] CHECK CONSTRAINT [WRK_UNT_ASSGNMNT_FK]
GO
ALTER TABLE [dbo].[EVENT]  WITH CHECK ADD  CONSTRAINT [EVENT_EVENT_TYP_FK] FOREIGN KEY([EVENT_TYPE_ID])
REFERENCES [dbo].[EVENT_TYPE] ([EVENT_TYPE_ID])
GO
ALTER TABLE [dbo].[EVENT] CHECK CONSTRAINT [EVENT_EVENT_TYP_FK]
GO
ALTER TABLE [dbo].[EVENT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_EVENT_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[EVENT] CHECK CONSTRAINT [WRK_UNT_EVENT_FK]
GO
ALTER TABLE [dbo].[MENTOR]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_TYPE_MNTR_FK] FOREIGN KEY([MENTOR_PROGRAM_TYPE_ID])
REFERENCES [dbo].[MENTOR_PROGRAM_TYPE] ([MENTOR_PROGRAM_TYPE_ID])
GO
ALTER TABLE [dbo].[MENTOR] CHECK CONSTRAINT [MNTR_PRGRM_TYPE_MNTR_FK]
GO
ALTER TABLE [dbo].[MENTOR]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_MNTR_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[MENTOR] CHECK CONSTRAINT [WRK_UNT_MNTR_FK]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_MNTR_PRGRM_DTL_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[MENTOR] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_MNTR_PRGRM_DTL_FK]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK1] FOREIGN KEY([MENTOR_MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK1]
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL]  WITH CHECK ADD  CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK2] FOREIGN KEY([MENTEE_MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MENTOR_PROGRAM_DETAIL] CHECK CONSTRAINT [MNTR_PRGRM_DTL_MIND_FK2]
GO
ALTER TABLE [dbo].[MIND]  WITH CHECK ADD  CONSTRAINT [R_65] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO
ALTER TABLE [dbo].[MIND] CHECK CONSTRAINT [R_65]
GO
ALTER TABLE [dbo].[MIND_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_ACTVTY_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MIND_ACTIVITY] CHECK CONSTRAINT [MIND_ACTVTY_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_MIND_ACTVTY_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[MIND_ACTIVITY] CHECK CONSTRAINT [WRK_UNT_MIND_ACTVTY_FK]
GO
ALTER TABLE [dbo].[MIND_CONTACT]  WITH CHECK ADD  CONSTRAINT [MIND_CNTCT_CNTCT_TYPE_FK] FOREIGN KEY([CONTACT_TYPE_ID])
REFERENCES [dbo].[CONTACT_TYPE] ([CONTACT_TYPE_ID])
GO
ALTER TABLE [dbo].[MIND_CONTACT] CHECK CONSTRAINT [MIND_CNTCT_CNTCT_TYPE_FK]
GO
ALTER TABLE [dbo].[MIND_CONTACT]  WITH CHECK ADD  CONSTRAINT [MIND_CNTCT_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MIND_CONTACT] CHECK CONSTRAINT [MIND_CNTCT_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_MINDROLE]  WITH CHECK ADD  CONSTRAINT [MIND_MINDROLE_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MIND_MINDROLE] CHECK CONSTRAINT [MIND_MINDROLE_FK]
GO
ALTER TABLE [dbo].[MIND_MINDROLE]  WITH CHECK ADD  CONSTRAINT [MIND_ROLE_MIND_FK] FOREIGN KEY([MIND_ROLE_ID])
REFERENCES [dbo].[MIND_ROLE] ([MIND_ROLE_ID])
GO
ALTER TABLE [dbo].[MIND_MINDROLE] CHECK CONSTRAINT [MIND_ROLE_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_ORGANIZATION]  WITH CHECK ADD  CONSTRAINT [MIND_ORG_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MIND_ORGANIZATION] CHECK CONSTRAINT [MIND_ORG_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_ORGANIZATION]  WITH CHECK ADD  CONSTRAINT [MIND_ORG_ORG_GRP_FK] FOREIGN KEY([ORGANIZATION_GROUP_ID])
REFERENCES [dbo].[ORGANIZATION_GROUP] ([ORGANIZATION_GROUP_ID])
GO
ALTER TABLE [dbo].[MIND_ORGANIZATION] CHECK CONSTRAINT [MIND_ORG_ORG_GRP_FK]
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_PRFL_ACT_PRFL_FK] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY] CHECK CONSTRAINT [MIND_PRFL_ACT_PRFL_FK]
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [MIND_PRFLE_ACTVTY_ACTVTY_FK] FOREIGN KEY([MIND_ACTIVITY_ID])
REFERENCES [dbo].[MIND_ACTIVITY] ([MIND_ACTIVITY_ID])
GO
ALTER TABLE [dbo].[MIND_PROFILE_ACTIVITY] CHECK CONSTRAINT [MIND_PRFLE_ACTVTY_ACTVTY_FK]
GO
ALTER TABLE [dbo].[MIND_TAG]  WITH CHECK ADD  CONSTRAINT [MIND_TAG_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[MIND_TAG] CHECK CONSTRAINT [MIND_TAG_MIND_FK]
GO
ALTER TABLE [dbo].[MIND_TAG]  WITH CHECK ADD  CONSTRAINT [MIND_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO
ALTER TABLE [dbo].[MIND_TAG] CHECK CONSTRAINT [MIND_TAG_TAG_FK]
GO
ALTER TABLE [dbo].[ORG_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [ORG_ACTVTY_ORG_ACTVTY_TYP_FK] FOREIGN KEY([ORG_ACTIVITY_TYPE_ID])
REFERENCES [dbo].[ORG_ACTIVITY_TYPE] ([ORG_ACTIVITY_TYPE_ID])
GO
ALTER TABLE [dbo].[ORG_ACTIVITY] CHECK CONSTRAINT [ORG_ACTVTY_ORG_ACTVTY_TYP_FK]
GO
ALTER TABLE [dbo].[ORG_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_ORG_ACTVTY_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[ORG_ACTIVITY] CHECK CONSTRAINT [WRK_UNT_ORG_ACTVTY_FK]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [PRE_ASSGMNT_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT] CHECK CONSTRAINT [PRE_ASSGMNT_MIND_FK]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_PRE_ASSNMNT_ARTFCT_FK] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT] CHECK CONSTRAINT [ARTFCT_PRE_ASSNMNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [PRE_ASSNMNT_ARTFCT_FK] FOREIGN KEY([PRE_ASSIGNMENT_ID])
REFERENCES [dbo].[PRE_ASSIGNMENT] ([PRE_ASSIGNMENT_ID])
GO
ALTER TABLE [dbo].[PRE_ASSIGNMENT_ARTIFACT] CHECK CONSTRAINT [PRE_ASSNMNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[PROFILE]  WITH CHECK ADD  CONSTRAINT [PROFILE_MIND_FK] FOREIGN KEY([MID])
REFERENCES [dbo].[MIND] ([MID])
GO
ALTER TABLE [dbo].[PROFILE] CHECK CONSTRAINT [PROFILE_MIND_FK]
GO
ALTER TABLE [dbo].[PROFILE]  WITH CHECK ADD  CONSTRAINT [PROFILE_PROFILE_TYPE_FK] FOREIGN KEY([PROFILE_TYPE_ID])
REFERENCES [dbo].[PROFILE_TYPE] ([PROFILE_TYPE_ID])
GO
ALTER TABLE [dbo].[PROFILE] CHECK CONSTRAINT [PROFILE_PROFILE_TYPE_FK]
GO
ALTER TABLE [dbo].[PROFILE_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_PRFL_TAG] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO
ALTER TABLE [dbo].[PROFILE_ARTIFACT] CHECK CONSTRAINT [ARTFCT_PRFL_TAG]
GO
ALTER TABLE [dbo].[PROFILE_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [PRFL_PRFL_TAG] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[PROFILE_ARTIFACT] CHECK CONSTRAINT [PRFL_PRFL_TAG]
GO
ALTER TABLE [dbo].[PROFILE_PRE_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [PRFL_PREASSGMNT_PREASSGNNT_FK] FOREIGN KEY([PRE_ASSIGNMENT_ID])
REFERENCES [dbo].[PRE_ASSIGNMENT] ([PRE_ASSIGNMENT_ID])
GO
ALTER TABLE [dbo].[PROFILE_PRE_ASSIGNMENT] CHECK CONSTRAINT [PRFL_PREASSGMNT_PREASSGNNT_FK]
GO
ALTER TABLE [dbo].[PROFILE_PRE_ASSIGNMENT]  WITH CHECK ADD  CONSTRAINT [PRFLE_ASSGNMENT_PRFLE_FK] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[PROFILE_PRE_ASSIGNMENT] CHECK CONSTRAINT [PRFLE_ASSGNMENT_PRFLE_FK]
GO
ALTER TABLE [dbo].[PROFILE_TAG]  WITH CHECK ADD  CONSTRAINT [PRFL_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO
ALTER TABLE [dbo].[PROFILE_TAG] CHECK CONSTRAINT [PRFL_TAG_TAG_FK]
GO
ALTER TABLE [dbo].[PROFILE_TAG]  WITH CHECK ADD  CONSTRAINT [PROFILE_TAG_PROFILE_FK] FOREIGN KEY([PROFILE_ID])
REFERENCES [dbo].[PROFILE] ([PROFILE_ID])
GO
ALTER TABLE [dbo].[PROFILE_TAG] CHECK CONSTRAINT [PROFILE_TAG_PROFILE_FK]
GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [PBLCTN_PBLCTN_TYP_FK] FOREIGN KEY([PUBLICATION_TYPE_ID])
REFERENCES [dbo].[PUBLICATION_TYPE] ([PUBLICATION_TYPE_ID])
GO
ALTER TABLE [dbo].[PUBLICATION] CHECK CONSTRAINT [PBLCTN_PBLCTN_TYP_FK]
GO
ALTER TABLE [dbo].[PUBLICATION]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_PBLCTN_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[PUBLICATION] CHECK CONSTRAINT [WRK_UNT_PBLCTN_FK]
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [TAG_ASSTN_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION] CHECK CONSTRAINT [TAG_ASSTN_TAG_FK]
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION]  WITH CHECK ADD  CONSTRAINT [TAG_ASSTN_TAG_TYPE_FK] FOREIGN KEY([TAG_GROUP_ID])
REFERENCES [dbo].[TAG_GROUP] ([TAG_GROUP_ID])
GO
ALTER TABLE [dbo].[TAG_ASSOCIATION] CHECK CONSTRAINT [TAG_ASSTN_TAG_TYPE_FK]
GO
ALTER TABLE [dbo].[TAG_GROUP]  WITH CHECK ADD  CONSTRAINT [TAG_TYPE_PRNT_TAG_FK] FOREIGN KEY([TAG_GROUP_ID])
REFERENCES [dbo].[TAG_GROUP] ([TAG_GROUP_ID])
GO
ALTER TABLE [dbo].[TAG_GROUP] CHECK CONSTRAINT [TAG_TYPE_PRNT_TAG_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_WRK_UNT_TYP_FK] FOREIGN KEY([WORK_UNIT_TYPE])
REFERENCES [dbo].[WORKUNIT_TYPE] ([WORK_UNIT_TYPE])
GO
ALTER TABLE [dbo].[WORK_UNIT] CHECK CONSTRAINT [WRK_UNT_WRK_UNT_TYP_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [ARTFCT_WRK_UNT_ARTFCT_FK] FOREIGN KEY([ARTIFACT_ID])
REFERENCES [dbo].[ARTIFACT] ([ARTIFACT_ID])
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT] CHECK CONSTRAINT [ARTFCT_WRK_UNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_WRK_UNT_ARTFCT_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[WORK_UNIT_ARTIFACT] CHECK CONSTRAINT [WRK_UNT_WRK_UNT_ARTFCT_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT_MIND]  WITH CHECK ADD  CONSTRAINT [R_66] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[WORK_UNIT_MIND] CHECK CONSTRAINT [R_66]
GO
ALTER TABLE [dbo].[WORK_UNIT_TAG]  WITH CHECK ADD  CONSTRAINT [PRJ_PRPSL_TAG_TAG_FK] FOREIGN KEY([TAG_ID])
REFERENCES [dbo].[TAG] ([TAG_ID])
GO
ALTER TABLE [dbo].[WORK_UNIT_TAG] CHECK CONSTRAINT [PRJ_PRPSL_TAG_TAG_FK]
GO
ALTER TABLE [dbo].[WORK_UNIT_TAG]  WITH CHECK ADD  CONSTRAINT [WRK_UNT_WRK_UNT_TAG_FK] FOREIGN KEY([WORK_UNIT_ID])
REFERENCES [dbo].[WORK_UNIT] ([WORK_UNIT_ID])
GO
ALTER TABLE [dbo].[WORK_UNIT_TAG] CHECK CONSTRAINT [WRK_UNT_WRK_UNT_TAG_FK]
GO
USE [master]
GO
ALTER DATABASE [CSGPortal] SET  READ_WRITE 
GO
